'use strict';
const {data:d,kind,brand,shellUi,assets={}}=JSON.parse(document.querySelector('#payload').textContent);
let lang=d.language||'es',page=0,priorFocus=null;
const presented=['immersive-class','masterclass','dynamic-commercial-decks'].includes(kind);
const ui={es:['Pausar animación','Reanudar animación','Proyectar','Imprimir','Anterior','Siguiente','completadas','Contexto','Ajustes','Copiar prompt','Copiado','No se pudo copiar; selecciona el texto','Completado ✓','Marcar completado','Notas de facilitación','Evidencia','Criterios de logro','Tiempo restante','Duración en minutos','Iniciar / pausar','Reiniciar','Revelar pregunta','Prompt completo','Ejemplo'],en:['Pause animation','Resume animation','Project','Print','Previous','Next','completed','Context','Settings','Copy prompt','Copied','Copy failed; select the text','Completed ✓','Mark completed','Facilitator notes','Evidence','Success criteria','Remaining time','Duration in minutes','Start / pause','Reset','Reveal question','Full prompt','Example'],pt:['Pausar animação','Retomar animação','Projetar','Imprimir','Anterior','Próximo','concluídas','Contexto','Configurações','Copiar prompt','Copiado','Não foi possível copiar; selecione o texto','Concluído ✓','Marcar concluído','Notas de facilitação','Evidência','Critérios de sucesso','Tempo restante','Duração em minutos','Iniciar / pausar','Reiniciar','Revelar pergunta','Prompt completo','Exemplo'],fr:['Mettre en pause','Reprendre l’animation','Projeter','Imprimer','Précédent','Suivant','terminées','Contexte','Réglages','Copier le prompt','Copié','Copie impossible ; sélectionnez le texte','Terminé ✓','Marquer terminé','Notes de facilitation','Preuves','Critères de réussite','Temps restant','Durée en minutes','Démarrer / pause','Réinitialiser','Révéler la question','Prompt complet','Exemple']};
Object.entries(shellUi).forEach(([language,labels])=>ui[language].push(...labels));
const labels={es:{objectives:'Objetivos',demonstration:'Demostración',practice:'Práctica',checkpoints:'Comprobación',reflection:'Reflexión',transfer:'Transferencia',references:'Referencias',materials:'Materiales',training:'Plan de la sesión',answer:'Revelar respuesta',criterion:'Criterio',minutes:'minutos'},en:{objectives:'Objectives',demonstration:'Demonstration',practice:'Practice',checkpoints:'Knowledge check',reflection:'Reflection',transfer:'Transfer',references:'References',materials:'Materials',training:'Session plan',answer:'Reveal answer',criterion:'Criterion',minutes:'minutes'},pt:{objectives:'Objetivos',demonstration:'Demonstração',practice:'Prática',checkpoints:'Verificação',reflection:'Reflexão',transfer:'Transferência',references:'Referências',materials:'Materiais',training:'Plano da sessão',answer:'Revelar resposta',criterion:'Critério',minutes:'minutos'},fr:{objectives:'Objectifs',demonstration:'Démonstration',practice:'Pratique',checkpoints:'Vérification',reflection:'Réflexion',transfer:'Transfert',references:'Références',materials:'Matériel',training:'Plan de séance',answer:'Révéler la réponse',criterion:'Critère',minutes:'minutes'}};
const T=n=>(ui[lang]||ui.es)[n],B=key=>(labels[lang]||labels.es)[key];
const key='frames-aula:'+location.pathname+':'+JSON.stringify(d.title),state=(()=>{try{return JSON.parse(localStorage.getItem(key))||{values:{},done:{}}}catch{return {values:{},done:{}}}})();
const save=()=>{try{localStorage.setItem(key,JSON.stringify(state))}catch{}};
const L=x=>typeof x==='object'&&x!==null?(x[lang]??x.es??Object.values(x)[0]??''):String(x??'');
const displayText=text=>String(text).replace(/\[(METODOLOGIA|NEUROCIENCIA|PEDAGOGIA|INFERENCIA|SUPUESTO)\]/g,(_,tag)=>tag==='SUPUESTO'?({es:'(supuesto)',en:'(assumption)',pt:'(suposição)',fr:'(hypothèse)'}[lang]||'(supuesto)'):tag==='INFERENCIA'?({es:'(inferencia)',en:'(inference)',pt:'(inferência)',fr:'(inférence)'}[lang]||'(inferencia)'):'').trim();
const E=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=['pre','textarea','input'].includes(tag)?text:displayText(text);if(cls)e.className=cls;return e};
const main=document.querySelector('main');document.body.dataset.kind=kind;
document.body.dataset.theme=d.theme||((d.authoringPolicy?.origin==='new'&&['immersive-class','dynamic-commercial-decks'].includes(kind))?'dark':'light');
if(d._mobile)document.body.classList.add('mobile-edition');document.querySelector('#brand').textContent=brand.name;
const select=document.querySelector('#language');(d.languages||['es']).forEach(x=>{const o=E('option',x);o.value=x;select.append(o)});select.value=lang;select.onchange=()=>{lang=select.value;document.documentElement.lang=lang;render()};
function fields(s){return [...(s.fields||[]),...(s.settings||[]).map(f=>({...f,setting:true}))]}
function prompt(s){return L(s.prompt).replace(/\{\{(.*?)\}\}/g,(_,k)=>state.values[s.id+':'+k]??L(fields(s).find(f=>f.key===k)?.default??''))}
function localAsset(s,type,id){const base=s.id+':'+type+':'+id+':'+lang,raw=assets[base];if(!raw)return null;const decode=text=>document.importNode(new DOMParser().parseFromString(text,'image/svg+xml').documentElement,true);const node=decode(raw);node.classList.add(type==='scene'?'scene':'asset-icon');if(type==='scene'&&assets[base+':mobile']){const variants=E('div',undefined,'scene-variants'),mobile=decode(assets[base+':mobile']);node.classList.add('scene-desktop');mobile.classList.add('scene','scene-portrait');variants.append(node,mobile);return variants}return node}
function scene(s){const fromBank=localAsset(s,'scene',s.scene);if(fromBank)return fromBank;
 const NS='http://www.w3.org/2000/svg',svg=document.createElementNS(NS,'svg');svg.setAttribute('viewBox','0 0 600 180');svg.setAttribute('aria-hidden','true');svg.classList.add('scene');
 function shape(tag,attrs){const n=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));svg.append(n);return n}
 const accent=brand.colors.gold,ink=brand.colors.night;
 if(s.scene==='flow'){shape('path',{d:'M40 90 Q160 10 300 90 T560 90',fill:'none',stroke:ink,'stroke-width':5});for(let i=0;i<4;i++)shape('circle',{cx:80+i*140,cy:90,r:16,fill:accent})}
 if(s.scene==='steps'){for(let i=0;i<4;i++)shape('rect',{x:80+i*120,y:120-i*25,width:95,height:30+i*25,rx:8,fill:i%2?ink:accent})}
 if(s.scene==='orbit'){shape('ellipse',{cx:300,cy:90,rx:180,ry:65,fill:'none',stroke:ink,'stroke-width':3});shape('circle',{cx:300,cy:90,r:25,fill:ink});shape('circle',{cx:440,cy:90,r:17,fill:accent,class:'moving'})}
 if(s.scene==='gate'){shape('path',{d:'M150 155V30H450V155',fill:'none',stroke:ink,'stroke-width':10});shape('path',{d:'M220 95L275 140L390 45',fill:'none',stroke:accent,'stroke-width':12})}
 if(s.scene==='contrast'){shape('rect',{x:50,y:25,width:220,height:130,rx:16,fill:ink});shape('rect',{x:330,y:25,width:220,height:130,rx:16,fill:accent});shape('path',{d:'M285 90H315M305 80L315 90L305 100',fill:'none',stroke:ink,'stroke-width':4})}
 return svg;
}
function textBlock(parent,title,value,disclose=false){if(value===undefined||value===null||value==='')return;const node=E(disclose?'details':'div',undefined,'content-block');node.append(E(disclose?'summary':'h3',title));if(Array.isArray(value)){const list=E('ul');value.forEach(x=>list.append(E('li',L(x))));node.append(list)}else node.append(E('p',L(value)));parent.append(node)}
function references(parent,items){if(!items?.length)return;const details=E('details',undefined,'references');details.append(E('summary',B('references')));items.forEach(item=>details.append(E('p',typeof item==='string'?item:[L(item.title),item.source,item.sha256].filter(Boolean).join(' · '))));parent.append(details)}
const clocks=new Map();
function remaining(clock){return clock.running?Math.max(0,Math.ceil((clock.deadline-Date.now())/1000)):clock.remaining}
function format(seconds){return Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0')}
setInterval(()=>{for(const [id,clock] of clocks){const seconds=remaining(clock);const node=document.getElementById('timer-'+id);if(node)node.textContent=format(seconds);if(clock.running&&seconds===0){clock.running=false;clock.remaining=0;node?.setAttribute('aria-live','assertive');document.getElementById('timer-toggle-'+id)?.setAttribute('aria-pressed','false')}}},250);
function timerControl(parent,id,minutes=5){if(!clocks.has(id))clocks.set(id,{remaining:minutes*60,running:false,deadline:0});const clock=clocks.get(id),box=E('fieldset',undefined,'timer-controls');box.append(E('legend',T(17)));const output=E('output',format(remaining(clock)),'timer');output.id='timer-'+id;output.setAttribute('aria-label',T(17));box.append(output);const input=E('input');input.type='number';input.min='1';input.max='480';input.value=String(minutes);input.setAttribute('aria-label',T(18));input.onchange=()=>{if(!clock.running){clock.remaining=Math.min(480,Math.max(1,Number(input.value)||minutes))*60;output.textContent=format(clock.remaining)}};box.append(input);const start=E('button',T(19));start.id='timer-toggle-'+id;start.setAttribute('aria-pressed',String(clock.running));start.onclick=()=>{if(clock.running){clock.remaining=remaining(clock);clock.running=false}else if(clock.remaining>0){clock.deadline=Date.now()+clock.remaining*1000;clock.running=true}start.setAttribute('aria-pressed',String(clock.running));output.textContent=format(remaining(clock))};const reset=E('button',T(20));reset.onclick=()=>{clock.running=false;clock.remaining=Math.min(480,Math.max(1,Number(input.value)||minutes))*60;output.textContent=format(clock.remaining);start.setAttribute('aria-pressed','false');output.removeAttribute('aria-live')};box.append(start,reset);parent.append(box)}
function render(){document.documentElement.lang=lang;document.title=L(d.title);document.querySelector('.skip').textContent=T(25);select.setAttribute('aria-label',T(26));document.querySelector('nav').setAttribute('aria-label',T(27));document.querySelector('footer').textContent='RENDERED_DRAFT · '+T(24);main.replaceChildren();main.append(E('h1',L(d.title),'document-title'));
 if(d.thesis){const thesis=E('details',undefined,'thesis');thesis.append(E('summary',L(d.thesis.title||d.thesis)));(d.thesis.pillars||[]).forEach(p=>thesis.append(E('p',p.achieves?L(p.achieves)+' · '+L(p.proof):L(p))));main.append(thesis)}
 textBlock(main,B('objectives'),d.objectives,presented);if(d.training){const plan=E('details',undefined,'training-plan');plan.append(E('summary',B('training')+(d.training.durationMinutes?' · '+d.training.durationMinutes+' '+B('minutes'):'')));if(d.training.audience)plan.append(E('p',L(d.training.audience)));textBlock(plan,B('materials'),d.training.materials);(d.training.runOfShow||[]).forEach(item=>{const a=E('a',item.sectionId+' · '+item.minutes+' '+B('minutes'));a.href='#'+item.sectionId;a.onclick=e=>{e.preventDefault();moveTo(d.sections.findIndex(s=>s.id===item.sectionId))};plan.append(a);if(item.notes)plan.append(E('p',L(item.notes)))});main.append(plan)}
 d.sections.forEach((s,i)=>{const section=E('section',undefined,'card');section.id=s.id;section.dataset.layout=s.layout||'auto';section.hidden=presented&&i!==page;section.append(E('h2',L(s.title)));if(kind!=='lean-coffee'){const body=E('p',L(s.body),'section-body');if(s.reveal){body.hidden=true;const reveal=E('button',T(21));reveal.setAttribute('aria-expanded','false');reveal.onclick=()=>{body.hidden=!body.hidden;reveal.setAttribute('aria-expanded',String(!body.hidden))};section.append(reveal)}section.append(body)};
 if(s.scene){const visual=E('div',undefined,'visual-region');visual.append(scene(s));section.append(visual)}
 (s.assetRefs||[]).forEach(ref=>{const asset=localAsset(s,ref.kind,ref.id);if(asset){const fig=E('figure',undefined,'selected-asset');fig.append(asset);if(ref.label)fig.append(E('figcaption',L(ref.label)));section.append(fig)}});
 for(const field of ['cols','cards'])if(s[field]?.length){const grid=E('div',undefined,'component-grid');s[field].forEach(item=>{const card=E('article',undefined,'component-card');if(item.icon){const icon=localAsset(s,'icon',item.icon);if(icon)card.append(icon)}if(item.tag)card.append(E('span',L(item.tag),'badge'));card.append(E('h3',L(item.title)));if(item.body)card.append(E('p',L(item.body)));if(item.items){const list=E('ul');item.items.forEach(x=>list.append(E('li',L(x))));card.append(list)}grid.append(card)});section.append(grid)}
 if(s.metrics?.length){const metrics=E('dl',undefined,'metrics');s.metrics.forEach(item=>{const block=E('div');block.append(E('dt',L(item.label)),E('dd',L(item.value),'metric-value'));if(item.detail)block.append(E('dd',L(item.detail)));metrics.append(block)});section.append(metrics)}
 if(s.badges?.length){const badges=E('div',undefined,'badges');s.badges.forEach(item=>{const badge=E('span',L(item.label),'badge');if(item.icon){const icon=localAsset(s,'icon',item.icon);if(icon)badge.prepend(icon)}if(item.detail)badge.append(E('small',L(item.detail)));badges.append(badge)});section.append(badges)}
 textBlock(section,B('objectives'),s.objectives,true);textBlock(section,T(16),s.acceptance,true);
 for(const field of ['demonstration','practice','reflection','transfer'])textBlock(section,B(field),s[field],presented);
 if(s.checkpoints?.length){const checks=E('div',undefined,'checkpoints');checks.append(E('h3',B('checkpoints')));s.checkpoints.forEach(item=>{const check=E('div',undefined,'checkpoint');check.append(E('p',L(item.question)));if(item.criterion)check.append(E('p',B('criterion')+': '+L(item.criterion)));if(item.answer){const answer=E('details');answer.append(E('summary',B('answer')),E('p',L(item.answer)));check.append(answer)}checks.append(check)});section.append(checks)}
 if(s.durationMinutes&&kind==='immersive-class')timerControl(section,s.id,s.durationMinutes);
 if(fields(s).length){const context=E('fieldset');context.append(E('legend',T(7)));const settings=E('details');settings.append(E('summary',T(8)));fields(s).forEach(f=>{const label=E('label',L(f.label)),input=E('textarea');input.value=state.values[s.id+':'+f.key]??L(f.default??'');input.oninput=()=>{state.values[s.id+':'+f.key]=input.value;save();const pre=section.querySelector('pre');if(pre)pre.textContent=prompt(s)};label.append(input);(f.setting?settings:context).append(label)});section.append(context);if(settings.children.length>1)section.append(settings)}
 if(s.prompt){const disclosure=E('details');disclosure.open=kind==='workbook';disclosure.append(E('summary',T(22)),E('pre',prompt(s)));section.append(disclosure);const copy=E('button',T(9));copy.onclick=async()=>{const text=prompt(s);let success=false;try{await navigator.clipboard.writeText(text);success=true}catch{const t=E('textarea');t.value=text;t.setAttribute('aria-label',T(22));section.append(t);t.select();try{success=document.execCommand('copy')}catch{}if(success){t.remove();copy.focus()}}copy.textContent=T(success?10:11)};section.append(copy)}
 if(s.exemplar){const ex=E('details');ex.append(E('summary',T(23)),E('p',L(s.exemplar)));section.append(ex)}
 for(const field of ['table','matrix'])if(s[field]){const table=E('table'),head=E('thead'),tr=E('tr');if(s[field].caption)table.append(E('caption',L(s[field].caption)));s[field].headers.forEach(x=>{const th=E('th',L(x));th.scope='col';tr.append(th)});head.append(tr);table.append(head);const body=E('tbody');s[field].rows.forEach(row=>{const line=E('tr');row.forEach(x=>line.append(E('td',L(x))));body.append(line)});table.append(body);const wrap=E('div',undefined,'table-region');wrap.tabIndex=0;wrap.setAttribute('role','region');wrap.setAttribute('aria-label',L(s[field].caption||s.title));wrap.append(table);section.append(wrap)}
 (s.accordion||[]).forEach(item=>{const details=E('details');details.append(E('summary',L(item.title)),E('p',L(item.body)));section.append(details)});
 if(s.tabs?.length){const tablist=E('div',undefined,'tablist');tablist.setAttribute('role','tablist');const panels=[],buttons=[];s.tabs.forEach((item,n)=>{const button=E('button',L(item.title)),panel=E('div');button.id=s.id+'-tab-'+n;panel.id=s.id+'-panel-'+n;button.setAttribute('role','tab');button.setAttribute('aria-controls',panel.id);panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby',button.id);panel.textContent=L(item.body);panel.tabIndex=0;panel.hidden=n!==0;button.setAttribute('aria-selected',String(n===0));button.tabIndex=n===0?0:-1;buttons.push(button);panels.push(panel);button.onclick=()=>choose(n);button.onkeydown=e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();e.stopPropagation();const next=e.key==='Home'?0:e.key==='End'?buttons.length-1:(n+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;choose(next);buttons[next].focus()}};tablist.append(button)});function choose(n){buttons.forEach((b,i)=>{b.setAttribute('aria-selected',String(i===n));b.tabIndex=i===n?0:-1;panels[i].hidden=i!==n})}section.append(tablist,...panels)}
 const done=E('button',T(state.done[s.id]?12:13),'completion');done.setAttribute('aria-pressed',String(!!state.done[s.id]));done.onclick=()=>{state.done[s.id]=!state.done[s.id];save();done.textContent=T(state.done[s.id]?12:13);done.setAttribute('aria-pressed',String(!!state.done[s.id]));updatePosition()};section.append(done);if(kind==='workbook'){const projection=E('button',T(2));projection.onclick=()=>project(section);section.append(projection)}
 (s.links||[]).forEach(link=>{const a=E('a',L(link.label||link.href),'piece');a.href=link.href;section.append(a)});references(section,s.references);
 for(const field of ['notes','spoken','facilitatorNotes'])if(s[field]&&!new URLSearchParams(location.search).has('audience')){const notes=E('details',undefined,'notes');notes.append(E('summary',T(14)),E('p',L(s[field])));section.append(notes)}main.append(section)});
 if(d.facts?.length){const facts=E('details');facts.append(E('summary',T(15)));d.facts.forEach(f=>facts.append(E('p',L(f.text)+' · '+f.source+' · '+f.sha256)));main.append(facts)}
 textBlock(main,T(16),d.acceptance,presented);references(main,d.references);
 if(d.pieces?.length){const links=E('div',undefined,'pieces');d.pieces.forEach(p=>{const a=E('a',p.kind,'piece');a.href=p.href;links.append(a)});main.append(links)}
 if(kind==='lean-coffee'){const topic=d.sections[page];timerControl(main,'topic-'+topic.id,topic.durationMinutes||5);const reveal=E('button',T(21)),question=E('p',L(topic.body));question.hidden=true;reveal.setAttribute('aria-expanded','false');reveal.onclick=()=>{question.hidden=!question.hidden;reveal.setAttribute('aria-expanded',String(!question.hidden))};main.append(reveal,question)}
 updatePosition();document.querySelector('#prev').textContent=T(4);document.querySelector('#next').textContent=T(5);document.querySelector('#prev').disabled=page===0;document.querySelector('#next').disabled=page===d.sections.length-1;document.querySelector('#motion').textContent=T(document.body.classList.contains('paused')?1:0);document.querySelector('#projection').textContent=T(2);document.querySelector('button[onclick]').textContent=T(3)}
function updatePosition(){document.querySelector('#position').textContent=`${page+1} / ${d.sections.length} · ${d.sections.filter(s=>state.done[s.id]).length} ${T(6)}`}
function moveTo(n){if(n<0)return;page=Math.max(0,Math.min(d.sections.length-1,n));render();history.replaceState(null,'','#'+d.sections[page].id);if(presented)main.focus();else document.getElementById(d.sections[page].id)?.scrollIntoView({block:'start'})}
function move(n){moveTo(page+n)}
document.querySelector('#prev').onclick=()=>move(-1);document.querySelector('#next').onclick=()=>move(1);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('projection')){e.preventDefault();project();return}if(e.defaultPrevented||e.altKey||e.ctrlKey||e.metaKey||e.target.closest('input,textarea,select,[contenteditable],button,a,summary,[role="tab"],.table-region'))return;if(e.key==='ArrowRight'){e.preventDefault();move(1)}if(e.key==='ArrowLeft'){e.preventDefault();move(-1)}});
const motion=document.querySelector('#motion');motion.setAttribute('aria-pressed','false');motion.onclick=()=>{const paused=document.body.classList.toggle('paused');motion.textContent=T(paused?1:0);motion.setAttribute('aria-pressed',String(paused))};
function project(card){if(document.body.classList.contains('projection')){document.body.classList.remove('projection','projection-card');document.querySelector('.projected-card')?.classList.remove('projected-card');priorFocus?.focus()}else{priorFocus=document.activeElement;document.body.classList.add('projection');if(card){document.body.classList.add('projection-card');card.classList.add('projected-card')}(card||main).tabIndex=-1;(card||main).focus()}}
let printDetails=[],printHidden=[];window.addEventListener('beforeprint',()=>{printDetails=[...document.querySelectorAll('details:not(.notes)')].map(node=>[node,node.open]);printDetails.forEach(([node])=>node.open=true);printHidden=[...document.querySelectorAll('main [hidden]')].filter(node=>!node.closest('.notes'));printHidden.forEach(node=>node.hidden=false)});window.addEventListener('afterprint',()=>{printDetails.forEach(([node,open])=>node.open=open);printHidden.forEach(node=>node.hidden=true);printDetails=[];printHidden=[]});
document.querySelector('#projection').onclick=()=>project();const initial=d.sections.findIndex(s=>s.id===location.hash.slice(1));if(initial>=0)page=initial;render();
