// Import an explicitly chosen portable snapshot; --check is strictly read-only.
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { AULA_KINDS, Edition, digest } from '../engine/aula/catalog.ts';
import { repoPath } from '../engine/paths.ts';

const args = process.argv.slice(2);
const sourceArg = args[args.indexOf('--source') + 1];
if (!args.includes('--source') || !sourceArg)
  throw new Error('usage: sync-aula-packages.ts --source <portable skills directory> [--check]');
const source = path.resolve(sourceArg);
const check = args.includes('--check');
type PackageMeta = { name: string; version: string; kind: string; edition: string };

// Only host metadata changes. The portable SKILL, engine and content stay exact.
// This projection is deterministic and idempotent, including in read-only checks.
function nativeMetadata(meta: PackageMeta, file: string, body: Buffer): Buffer {
  const commercial = meta.kind === 'dynamic-commercial-decks';
  const family = commercial ? 'deck.immersive' : 'aula';
  const familyFile = `registry/families/${family}.yml`;
  const source = `skills/aula/${meta.name}`;
  if (file === 'LINEAGE.yml') {
    const text = body.toString('utf8');
    if ((text.match(/^authority_refs:.*$/gm) ?? []).length !== 1)
      throw new Error(`one lineage authority_refs required: ${meta.name}`);
    return Buffer.from(
      text.replace(
        /^authority_refs:.*$/m,
        `authority_refs: [registry/aula-capabilities.json, docs/adr/0007-aula-y-decks-comerciales.md, ${familyFile}, domains/aula/index.ts]`,
      ),
    );
  }
  if (file !== 'context.md') return body;
  return Buffer.from(`<!--
GENERATED by scripts/sync-aula-packages.ts. Native Frames OS metadata projection; do not edit copies.
context_id: CTX-AULA-${meta.name.toUpperCase()}
-->

# Contexto: ${source}

## Propósito y activación

La familia \`${family}\` ejecuta \`${meta.kind}\` en edición \`${meta.edition}\`.
El catálogo verifica el paquete completo antes de resolver el handler. [CÓDIGO]

## Autoridad y carga mínima

Owner: MetodologIA. Autoridades del host:

- \`registry/aula-capabilities.json\`
- \`docs/adr/0007-aula-y-decks-comerciales.md\`
- \`${familyFile}\`
- \`domains/aula/index.ts\`

Primero: \`${source}/SKILL.md\`.
Solo bajo demanda: \`${source}/references/runtime.md\` y
\`${source}/examples/input.json\`. Diferir otras skills y fuentes privadas.

## Recorrido nativo

Familia: \`${family}\`. Facts: \`aula_format=${meta.kind}\`,
\`edition=${meta.edition}\`, \`renderer=frames-aula\`.
Pasos: ${commercial ? '\`D01\`, \`DC01\`, \`DC02\`, \`DC03\`, \`DC04\`, \`DC05\`' : '\`A01\`, \`A02\`, \`A03\`, \`A04\`, \`A05\`'}.
Handler material: \`aula.render\`; fuente y recibos usan \`frames-aula-v1\` y \`aula-receipt-v1\`.

\`pnpm frames route "PEDIDO"\` selecciona la capacidad;
\`pnpm frames start ${family} --request "PEDIDO" --fact aula_format=${meta.kind} --fact edition=${meta.edition} --fact renderer=frames-aula\`
inicia el run. Continuar con \`pnpm frames next RUN\`; retomar con \`pnpm frames status RUN\`.

## Gates y escritura

Gates humanos: \`direction\`, ${commercial ? '\`outcome\` (intake comercial), ' : ''}\`sources-and-spec\`, \`acceptance\`.
La persona emite \`pnpm frames approve RUN GATE\` desde su terminal; el agente nunca.
El renderer entrega bytes mediante \`ctx.write\` en el write set del run y produce un receipt hash-bound.
Los paquetes son fuentes de lectura; este contexto se regenera mediante \`scripts/sync-aula-packages.ts\`.
El CLI Python autónomo produce un borrador y no acredita los gates del run.

Estado de las piezas: \`RENDERED_DRAFT\`; aceptación humana y publicación son decisiones separadas.
Nunca persistir secretos, PII ni razonamiento privado. Devolver handoff al contexto padre.
`);
}

function files(
  root: string,
  prefix = '',
  adapt: (file: string, body: Buffer) => Buffer = (_file, body) => body,
): Record<string, string> {
  const out: Record<string, string> = {};
  for (const item of readdirSync(path.join(root, prefix), { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name),
  )) {
    if (item.name === '__pycache__' || item.name === '.DS_Store') continue;
    if (item.isSymbolicLink()) throw new Error(`symlink refused: ${prefix}${item.name}`);
    const rel = prefix + item.name;
    if (item.isDirectory()) Object.assign(out, files(root, rel + '/', adapt));
    else out[rel] = digest(adapt(rel, readFileSync(path.join(root, rel))));
  }
  return Object.fromEntries(Object.entries(out).sort(([a], [b]) => a.localeCompare(b)));
}
const entries = readdirSync(source, { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => {
    const dir = path.join(source, e.name);
    const meta = JSON.parse(readFileSync(path.join(dir, 'package.json'), 'utf8')) as PackageMeta;
    if (
      !AULA_KINDS.includes(meta.kind as (typeof AULA_KINDS)[number]) ||
      !Edition.options.includes(meta.edition as (typeof Edition.options)[number])
    )
      throw new Error(`unsupported package: ${e.name}`);
    if (e.name !== meta.name || !/^[a-z0-9-]+$/.test(meta.name)) throw new Error('package identity mismatch');
    return {
      ...meta,
      source: `skills/aula/${meta.name}`,
      handler: 'aula.render' as const,
      files: Object.fromEntries(
        Object.entries({
          ...files(dir, '', (file, body) => nativeMetadata(meta, file, body)),
          'context.md': digest(nativeMetadata(meta, 'context.md', Buffer.alloc(0))),
        }).sort(([a], [b]) => a.localeCompare(b)),
      ),
    };
  })
  .sort((a, b) => a.name.localeCompare(b.name));
const expectedCount = AULA_KINDS.length * Edition.options.length;
const pairs = new Set(entries.map((entry) => `${entry.kind}/${entry.edition}`));
if (entries.length !== expectedCount || pairs.size !== expectedCount)
  throw new Error(`exactly ${expectedCount} kind/edition combinations required`);
for (const kind of AULA_KINDS)
  for (const edition of Edition.options)
    if (!pairs.has(`${kind}/${edition}`)) throw new Error(`kind/edition missing: ${kind}/${edition}`);
const engineSource = path.join(source, entries[0]!.name, 'engine');
const engineFiles = files(engineSource);
for (const skill of entries)
  for (const [file, hash] of Object.entries(engineFiles))
    if (skill.files[`engine/${file}`] !== hash) throw new Error(`engine divergence: ${skill.name}/${file}`);
const catalog = {
  schema: 'aula-capabilities-v1',
  state: 'ACTIVE_LOCAL',
  engine: { source: 'engine/aula/runtime', files: engineFiles },
  capabilities: entries.map(({ name, version, kind, edition, source, handler, files }) => ({
    id: name,
    version,
    kind,
    edition,
    source,
    handler,
    files,
  })),
};
const text = JSON.stringify(catalog, null, 2) + '\n';
// Refresh only current supplemental hashes and append the two new workshops.
// Original Frames inventory rows keep their bytes and positions.
const inventoryFile = repoPath('verify/parity/frames-inventory.json');
const inventoryText = readFileSync(inventoryFile, 'utf8');
let nextInventory = inventoryText;
for (const entry of entries) {
  const pattern = new RegExp(
    `^(    \\{[^\\n]*"id": "${entry.name}"[^\\n]*"source_sha256": ")[a-f0-9]{64}("[^\\n]*\\},?)$`,
    'm',
  );
  if (!pattern.test(nextInventory)) {
    if (
      entry.kind !== 'workshop-immersive' ||
      !['edu-workshop-immersive', 'metodologia-edu-workshop-immersive'].includes(entry.name)
    )
      throw new Error(`supplemental inventory row missing: ${entry.name}`);
    const inventory = JSON.parse(nextInventory) as { entries: { id: string }[] };
    if (inventory.entries.some((row) => row.id === entry.name))
      throw new Error(`supplemental inventory identity collision: ${entry.name}`);
    const end = '\n  ]\n}\n';
    if (!nextInventory.endsWith(end)) throw new Error('supplemental inventory closing shape');
    const row = {
      kind: 'skill',
      id: entry.name,
      title: entry.name,
      source: `${entry.source}/SKILL.md`,
      source_sha256: entry.files['SKILL.md'],
      destination: 'aula',
    };
    const rowText = `{${Object.entries(row)
      .map(([key, value]) => `${JSON.stringify(key)}: ${JSON.stringify(value)}`)
      .join(', ')}}`;
    nextInventory = nextInventory.slice(0, -end.length) + ',\n    ' + rowText + end;
    continue;
  }
  nextInventory = nextInventory.replace(
    pattern,
    (_match: string, head: string, tail: string) => head + entry.files['SKILL.md'] + tail,
  );
}
if (check) {
  if (readFileSync(repoPath('registry/aula-capabilities.json'), 'utf8') !== text)
    throw new Error('catalog drift');
  for (const e of entries)
    if (JSON.stringify(files(repoPath(e.source))) !== JSON.stringify(e.files))
      throw new Error(`package drift: ${e.name}`);
  if (JSON.stringify(files(repoPath(catalog.engine.source))) !== JSON.stringify(engineFiles))
    throw new Error('engine drift');
  if (inventoryText !== nextInventory) throw new Error('supplemental inventory hashes drift');
} else {
  for (const e of entries) {
    const target = repoPath(e.source);
    if (existsSync(target)) rmSync(target, { recursive: true, force: true });
    mkdirSync(path.dirname(target), { recursive: true });
    for (const f of Object.keys(e.files)) {
      mkdirSync(path.dirname(path.join(target, f)), { recursive: true });
      const body = f === 'context.md' ? Buffer.alloc(0) : readFileSync(path.join(source, e.name, f));
      writeFileSync(path.join(target, f), nativeMetadata(e, f, body));
    }
  }
  const target = repoPath(catalog.engine.source);
  if (existsSync(target)) rmSync(target, { recursive: true, force: true });
  mkdirSync(target, { recursive: true });
  for (const f of Object.keys(engineFiles)) {
    mkdirSync(path.dirname(path.join(target, f)), { recursive: true });
    cpSync(path.join(engineSource, f), path.join(target, f));
  }
  writeFileSync(repoPath('registry/aula-capabilities.json'), text);
  if (inventoryText !== nextInventory) writeFileSync(inventoryFile, nextInventory);
}
console.log(
  `Aula: ${entries.length} packages, engine and catalog ${check ? 'verified without writes' : 'synchronized'}`,
);
